# config/app.yml for rails-settings-cached
defaults: &defaults
  home: forum
  engines:
    - forum
    - reading
    - shop
    - ops
  languages:
    - 'en-US'
    - 'zh-CN'
    - 'zh-TW'

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
